
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main
#in lint we have 5 steps
jobs:
    lint:
      name: lint code and docker file
      runs-on: ubuntu-latest
      steps:
        - name: chechout code
          uses: action/checkout@v3
        
        - name: setup python
          uses: action/setup-python@v4
          with:
            python-version: 3.11
        - name: install dependances
          run: |
            python -m pip install --upgrade pip
            pip install flake8 dockerfile-lint

        - name: lint python code
          run: flake8

        - name: lint docker file
          run: dockerfile-lint -f Dockerfile
        
    build:
        name: build docker Image
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: action/checkout@v3
        
          - name: build docker image
            run: docker build -t hive-box .
    test:
        name: unit tests
        runs-on: ubuntu-latest
        steps:
          - name: checkout code 
            uses: action/checkout@v3

          - name: setup python
            uses: action/setup-python@v4
            with:
              python-version: 3.11

          - name: install dependances
            run: |
              python -m pip install --upgrade pip
              pip install pytest requestes
          - name: run unit test
            run: pytest tests/
    version-test:
      name: test/version Endpoint
      runs-on: ubuntu-latest
      steps:
        - name: checkout code 
          uses: action/checkout@v3
        - name: build and run container
          run: |
            docker build -t hive-box .
            docker run -d -p 8000:8000 --name hive-box-container hive-box
            sleep 5
        - name: test /version endpoint
          run: |
               curl -s http://127.0.0.1:8000/version | grep "app version"
        
        - name: stop and remove container
          run: dicker rm -f hive-box-container
    openssf-scorecard:
        name: OpenSSF Scorecard
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Run OpenSSF Scorecard
            uses: ossf/scorecard-action@v2
            with:
              results-file: results.json

          

